apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-db"
  labels:
    app: "{{ .Release.Name }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}"
        tier: mysql
    spec:
      containers:
        - image: mysql:5.6
          name: "{{ .Release.Name }}-db"
          env:
            - name: MYSQL_USER
              value: wordpress
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          ports:
            - containerPort: 3306
              name: "{{ .Release.Name }}-db"
          volumeMounts:
            - name: persistent-storage
              mountPath: /var/lib/mysql
              subPath: "{{ .Release.Name }}/db"
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: wp-efs-claim
