apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Release.Name }}"
spec:
  ports:
    - port: 80
  selector:
    app: "{{ .Release.Name }}"
    tier: frontend
  type: ClusterIP
