apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-site"
  labels:
    app: "{{ .Release.Name }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}"
        tier: frontend
    spec:
      containers:
        - image: "{{ .Values.wordpress.image.repository }}:{{ .Values.wordpress.image.tag }}"
          name: "{{ .Release.Name }}-site"
          env:
            - name: WORDPRESS_DB_HOST
              value: "{{ .Release.Name }}-db.wordpress"
            - name: WORDPRESS_DB_NAME
              value: "{{ .Values.mysql.name }}"
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          ports:
            - containerPort: 80
              name: site
          volumeMounts:
            - name: persistent-storage
              mountPath: /var/www/html
              subPath: "{{ .Release.Name }}/site"
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: wp-efs-claim
