output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value = module.eks.config_map_aws_auth
}

output "region" {
  description = "AWS region."
  value = var.region
}

output "db_host" {
  description = "Wordpress Database Host"
  value = aws_rds_cluster.aurora.endpoint
}

output "db_port" {
  description = "Wordpress Database Port"
  value = aws_rds_cluster.aurora.port
}

output "efs_file_system_id" {
  description = "Amazon EFS file system ID"
  value = aws_efs_file_system.nfs.id
}
