version: 0.2

env:
  variables:
    MASTER_USERNAME: wordpress
    MASTER_PASSWORD: d29yZHByZXNz
  secrets-manager:
    DOCKER_USERNAME: xilution-docker-hub-credentials:username
    DOCKER_PASSWORD: xilution-docker-hub-credentials:password

phases:
  pre_build:
    commands:
      - . ./scripts/assume-role.sh
      - ./scripts/terraform-init-trunk.sh
  build:
    commands:
      - ./scripts/terraform-plan-trunk.sh
      - ./scripts/terraform-apply-trunk.sh
