---
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProductName:
    Type: String
  Environment:
    Type: String

Conditions:
  CreateTestResources: !Equals [ !Ref Environment, test ]

Resources:
  BackendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProductName}-terraform-backend-${Environment}'
      VersioningConfiguration:
        Status: Enabled

  LockTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub '${ProductName}-terraform-backend-lock'
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
