version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - |
        terraform init \
          -backend-config="role_arn=arn:aws:iam::$CLIENT_AWS_ACCOUNT:role/xilution-developer-role" \
          -backend-config="key=xilution-cms-penguin/$XILUTION_PENGUIN_INSTANCE_ID/terraform.tfstate" \
          -backend-config="bucket=xilution-terraform-backend-state-bucket-$CLIENT_AWS_ACCOUNT" \
          -backend-config="dynamodb_table=xilution-terraform-backend-lock-table"
  build:
    commands:
      - |
        terraform apply \
          -var="organization_id=$XILUTION_ORGANIZATION_ID" \
          -var="master_username=$WORDPRESS_DB_USERNAME" \
          -var="master_password=$WORDPRESS_DB_PASSWORD" \
          -auto-approve
