version: 0.2

phases:
  pre_build:
    commands:
      - |
        aws sts assume-role \
          --role-arn arn:aws:iam::$CLIENT_AWS_ACCOUNT:role/xilution-developer-role \
          --role-session-name xilution-client-session > aws-creds.json
      - export AWS_ACCESS_KEY_ID=`cat aws-creds.json | jq -r '.Credentials.AccessKeyId'`
      - export AWS_SECRET_ACCESS_KEY=`cat aws-creds.json | jq -r '.Credentials.SecretAccessKey'`
      - export AWS_SESSION_TOKEN=`cat aws-creds.json | jq -r '.Credentials.SessionToken'`
      - |
        terraform init \
          -backend-config="key=xilution-cms-penguin/$PIPELINE_ID/terraform.tfstate" \
          -backend-config="bucket=xilution-terraform-backend-state-bucket-$CLIENT_AWS_ACCOUNT" \
          -backend-config="dynamodb_table=xilution-terraform-backend-lock-table"
  build:
    commands:
      - |
        terraform apply \
          -var="organization_id=$XILUTION_ORGANIZATION_ID" \
          -var="pipeline_id=$PIPELINE_ID" \
          -var="client_aws_account=$CLIENT_AWS_ACCOUNT" \
          -var="k8s_cluster_name=$K8S_CLUSTER_NAME" \
          -auto-approve
