version: 0.2

phases:
  pre_build:
    commands:
      - |
        . ./scripts/pre-build.sh \
          $CLIENT_AWS_ACCOUNT \
          xilution-developer-role \
          $K8S_CLUSTER_NAME \
          $PENGUIN_PIPELINE_ID \
          $CODEBUILD_SRC_DIR
  build:
    commands:
      - |
        terraform destroy \
          -var="penguin_pipeline_id=$PENGUIN_PIPELINE_ID" \
          -var="gitlab_token=$GITLAB_TOKEN" \
          -var="gitlab_project=$WEBHOOK_SOURCE_PREFIX" \
          -var="gitlab_repository=$WEBHOOK_SOURCE_REPOSITORY" \
          -auto-approve \
          $CODEBUILD_SRC_DIR/terraform/webhooks/gitlab
