#!/bin/bash

cat <<EOF >./properties.txt
AWS_REGION=$AWS_REGION
AWS_ACCOUNT=$AWS_ACCOUNT
AWS_PROFILE=$AWS_PROFILE
XILUTION_ENVIRONMENT=$XILUTION_ENVIRONMENT
XILUTION_ORGANIZATION_ID=$XILUTION_ORGANIZATION_ID
XILUTION_PENGUIN_INSTANCE_ID=09834225195643a9852d6e39b770712c
K8S_CLUSTER_NAME=xilution-k8s
GITHUB_TOKEN=$GITHUB_TOKEN
WORDPRESS_DB_USERNAME=wordpress
WORDPRESS_DB_PASSWORD=$(echo -n 'wordpress' | base64)
EOF
