version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - export IMAGE_NAME=`yq r config.yaml name`
      - export IMAGE_VERSION=`yq r config.yaml version`
      - aws ecr create-repository --repository-name xilution/$XILUTION_ORGANIZATION_ID/$IMAGE_NAME | true
  build:
    commands:
      - docker build -t xilution/$XILUTION_ORGANIZATION_ID/$IMAGE_NAME .
  post_build:
    commands:
      - aws ecr get-login --no-include-email | /bin/bash
      - docker tag xilution/$XILUTION_ORGANIZATION_ID/$IMAGE_NAME $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/xilution/$XILUTION_ORGANIZATION_ID/$IMAGE_NAME:$IMAGE_VERSION
      - docker push $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/xilution/$XILUTION_ORGANIZATION_ID/$IMAGE_NAME
      - |
        cat <<EOF >./image.yaml
        wordpress:
          image:
            repository: $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/xilution/$XILUTION_ORGANIZATION_ID/$IMAGE_NAME
            tag: $IMAGE_VERSION
        EOF
artifacts:
  files:
    - image.yaml
